authors:
  Sujith:
    name: Sujith
    description: Sujith Quintelier - Azure Architect # Author description
    avatar: https://s.gravatar.com/avatar/a05c76c8e3ee75a331388cf94b006d18?s=270%27)         # Author avatar
    slug: sujith           # Author profile slug
    url: https://sujithq.github.io            # Author website URL